# Generated by Django 5.1 on 2024-10-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_company_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Graphic Design', 'DG'), ('Branding', 'B'), ('Promotional Video', 'PV'), ('Digital Campaigns', 'DC'), ('Web Design and Development', 'WD')], max_length=50),
        ),
    ]
