# Generated by Django 5.1 on 2024-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_code_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('DG', 'Graphic Design'), ('B', 'Branding'), ('PV', 'Promotional Video'), ('DC', 'Digital Campaigns'), ('WD', 'Web Design and Development')], max_length=50),
        ),
    ]
