# Generated by Django 5.1 on 2024-10-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='files',
        ),
        migrations.AddField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requests/'),
        ),
        migrations.AddField(
            model_name='request',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
